name = "timezone-bot"

main = "worker.js"

compatibility_date = "2026-09-12"

[durable_objects]
bindings = [
  { name = "TIMEZONE_BOT", class_name = "TimezoneBot" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TimezoneBot"]